import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import sharp from 'sharp';

const root = fileURLToPath(new URL('../', import.meta.url));
const tokens = JSON.parse(await readFile(path.join(root, 'tokens.json'), 'utf8'));
const source = await readFile(path.join(root, 'source/logo-master.svg'), 'utf8');
const c = tokens.color;
const group = (id) => {
  const match = source.match(new RegExp(`<g id="${id}"[^>]*>([\\s\\S]*?)</g>`));
  if (!match) throw new Error(`Missing ${id} in logo-master.svg`);
  return match[1];
};
const symbol = group('symbol');
const wordmark = group('wordmark');
const mark = (fill) => `<g fill="${fill}">${symbol}</g>`;
const lettering = (fill) => `<g fill="${fill}">${wordmark}</g>`;
const logo = (symbolFill, textFill) => mark(symbolFill) + lettering(textFill);
const svg = (viewBox, body, label = 'Déjà Vu') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="${label}"><title>${label}</title>${body}</svg>\n`;
const rect = (x, y, width, height, fill) => `<rect x="${x}" y="${y}" width="${width}" height="${height}" fill="${fill}"/>`;

for (const dir of ['logos', 'icons', 'social']) await mkdir(path.join(root, dir), { recursive: true });

async function save(name, content, width, background) {
  await writeFile(path.join(root, `${name}.svg`), content);
  let output = sharp(Buffer.from(content)).resize({ width });
  if (background) output = output.flatten({ background });
  await output.png().toFile(path.join(root, `${name}.png`));
}

for (const [name, a, b] of [
  ['primary', c.blue, c.ink],
  ['reverse', c.sky, c.ivory],
  ['ink', c.ink, c.ink],
  ['ivory', c.ivory, c.ivory],
]) {
  await save(`logos/dejavu-${name}`, svg('229 196 1464 434', logo(a, b)), 2400);
}

await save('logos/dejavu-primary-on-ivory', svg('157 124 1608 578', rect(157, 124, 1608, 578, c.ivory) + logo(c.blue, c.ink)), 2400, c.ivory);
await save('logos/dejavu-reverse-on-ink', svg('157 124 1608 578', rect(157, 124, 1608, 578, c.ink) + logo(c.sky, c.ivory)), 2400, c.ink);

for (const [name, color] of [['blue', c.blue], ['ink', c.ink], ['ivory', c.ivory], ['sky', c.sky]]) {
  await save(`logos/dejavu-mark-${name}`, svg('205 172 484 484', mark(color), 'Déjà Vu symbol'), 1024);
}
await save('logos/dejavu-wordmark-ink', svg('686 274 1008 328', lettering(c.ink)), 2000);
await save('logos/dejavu-wordmark-ivory', svg('686 274 1008 328', lettering(c.ivory)), 2000);

const centeredMark = (fill, size) => `<g transform="translate(${size / 2} ${size / 2}) scale(${size * 0.62 / 388}) translate(-447 -414)">${mark(fill)}</g>`;
const app = svg('0 0 1024 1024', rect(0, 0, 1024, 1024, c.blue) + centeredMark(c.ivory, 1024), 'Déjà Vu app icon');
const darkApp = svg('0 0 1024 1024', rect(0, 0, 1024, 1024, c.ink) + centeredMark(c.sky, 1024), 'Déjà Vu app icon, dark');
await save('icons/app-icon', app, 1024, c.blue);
await save('icons/app-icon-dark', darkApp, 1024, c.ink);
for (const size of [16, 32, 180, 192, 512]) {
  const name = size === 180 ? 'apple-touch-icon' : `icon-${size}`;
  await sharp(Buffer.from(app)).resize(size, size).png().toFile(path.join(root, 'icons', `${name}.png`));
}
await writeFile(path.join(root, 'icons/favicon.svg'), app);

// ICO wraps the same PNG exports; each directory entry stores its image offset.
const icoSizes = [16, 32];
const icoImages = await Promise.all(icoSizes.map(size => readFile(path.join(root, `icons/icon-${size}.png`))));
const header = Buffer.alloc(6 + icoImages.length * 16);
header.writeUInt16LE(1, 2);
header.writeUInt16LE(icoImages.length, 4);
let offset = header.length;
icoImages.forEach((data, i) => {
  const entry = 6 + i * 16;
  header[entry] = icoSizes[i]; header[entry + 1] = icoSizes[i];
  header.writeUInt16LE(1, entry + 4); header.writeUInt16LE(32, entry + 6);
  header.writeUInt32LE(data.length, entry + 8); header.writeUInt32LE(offset, entry + 12);
  offset += data.length;
});
await writeFile(path.join(root, 'icons/favicon.ico'), Buffer.concat([header, ...icoImages]));

const socialLogo = `<g transform="translate(600 270) scale(.68) translate(-961 -413)">${logo(c.blue, c.ink)}</g>`;
const social = svg('0 0 1200 630', rect(0, 0, 1200, 630, c.ivory) + socialLogo + rect(88, 491, 1024, 3, c.line) + `<text x="600" y="548" text-anchor="middle" font-family="Arial, sans-serif" font-size="25" fill="${c.ink}">You've met before. Now you'll remember.</text><text x="600" y="591" text-anchor="middle" font-family="Arial, sans-serif" font-size="19" fill="${c.blue}">dejavu.blue</text>`, 'Déjà Vu — You’ve met before. Now you’ll remember.');
await save('social/social-card', social, 1200, c.ivory);

const lines = ['/* Generated by npm run build. Edit tokens.json. */', ':root {'];
for (const [name, value] of Object.entries(c)) lines.push(`  --dv-color-${name.replace(/[A-Z]/g, x => '-' + x.toLowerCase())}: ${value};`);
lines.push(`  --dv-font-family: "${tokens.font.family}", ${tokens.font.fallback};`);
for (const [name, value] of Object.entries(tokens.font.weights)) lines.push(`  --dv-weight-${name}: ${value};`);
for (const [name, value] of Object.entries(tokens.font.size)) lines.push(`  --dv-text-${name}: ${value};`);
for (const [name, value] of Object.entries(tokens.font.lineHeight)) lines.push(`  --dv-leading-${name}: ${value};`);
for (const [name, value] of Object.entries(tokens.radius)) lines.push(`  --dv-radius-${name}: ${value};`);
for (const [name, value] of Object.entries(tokens.space)) lines.push(`  --dv-space-${name}: ${value};`);
lines.push('}', '', '@font-face {', '  font-family: "Manrope";', '  src: url("./fonts/manrope-variable.ttf") format("truetype");', '  font-style: normal;', '  font-weight: 200 800;', '  font-display: swap;', '}', '');
await writeFile(path.join(root, 'tokens.css'), lines.join('\n'));
console.log('Exported SVG and PNG logos, icons, social card, and CSS tokens.');
